<?php

/* Assets */
$this->headLink()->appendStylesheet($this->basePath('/asset/file-uploader/css/file-uploader.css'));
$this->inlineScript()->appendFile($this->basePath('/asset/file-uploader/js/file-uploader.js'));

$translator = $this->trydI18n()->translator('Tryd\FileUploader');

?>

<div class="tf-dndzone">
    <p><?php echo $translator->translate('Click here or drag and drop files from browser to add it.'); ?></p>

    <ul class="tf-dndzone-filelist">
        <?php

            //TODO: image list

        ?>
    </ul>
</div>
